import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { PageProps } from '../models/page-props';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ categories }: PageProps) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          {/* <Image src="" alt="" /> */}
          <Link href="/" passHref>Home</Link>
          <Link href="/events" passHref>Events</Link>
          <Link href="/about-us" passHref>About us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {categories.map((category) => (
          <Link href={`/events/${category.id}`} key={category.id} passHref>
            <div>
              <Image
                src={category.image}
                alt={category.title}
                width="200"
                height="100"
              />
              <h2>{category.title}</h2>
              <p>{category.description}</p>
            </div>
          </Link>
        ))}
      </main>
      <footer>Footer</footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json');

  return {
    props: {
      categories: events_categories,
    },
  };
}
