import Head from 'next/head';
import { Inter } from '@next/font/google';
import { PageProps } from '../models/page-props';
// import Button from '@mui/material/Button';
import styles from '../styles/Home.module.scss';
import HomePage from '../src/components/HomePage/HomePage';
import Footer from '../src/components/Footer/Footer';
import Header from '../src/components/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ categories }: PageProps) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage categories={categories} />
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json');

  return {
    props: {
      categories: events_categories,
    },
  };
}
